resource_group_name = "vault-rsg"
location            = "East US"
subnet_prefixes     = "192.168.1.0/24"
address_space       = "192.168.0.0/16"
cmd_script          = "https://raw.githubusercontent.com/satyamuralidhar/azure-terrafomr-vault/main/vault-install.sh?token=GHSAT0AAAAAAB2UFLX4RES3ZUYPUKGISWFKY5YINRQ"